title: Andres Garcia-Gomez
logo: assets/img/P1210467-modified.png
description: Detail oriented and results driven Applied and Computational Mathematics graduate with a strong foundation in
machine learning, data science, and statistical analysis. Experienced in building predictive models, optimizing
algorithms, and working with large datasets to derive actionable insights. Skilled in Python, data wrangling, and
visualization, with hands on experience in both academic and industry settings. Dean’s List recipient and
award winning leader.
show_downloads: true
theme: jekyll-theme-minimal
