title: Andres Garcia-Gomez
logo: assets/img/P1210467-modified.png
description: Applied and Computational Mathematics graduate with a strong foundation in machine learning and data analysis. Experienced in building predictive models, optimizing algorithms, and working with large datasets to evaluate trends and patterns.
show_downloads: true
theme: jekyll-theme-minimal
