title: Andres Garcia-Gomez
logo: assets/img/P1210467-modified.png
description: Recent graduate from the University of Southern California, seeking work in data science
show_downloads: true
theme: jekyll-theme-minimal
